wahoo: gpt-utils: Add missing gpt-utils.h * If it is missing, the following build error will appear
hardware/qcom/bootctrl/boot_control.cpp:49:10: fatal error: 'gpt-utils.h' file not found
         ^~~~~~~~~~~~~
1 error generated.

* From https://github.com/PixelDevTeam/hardware_qcom_msm8998
Signed-off-by: ReallySnow <reallysnow233@gmail.com>
Change-Id: I6b6516c6b2e7dc58395c8796c8c28460ad8e4cea